ENV_NAME="phabricator"
# PHABRICATOR_PATH=/path/to/phabricator
# Path to folder that includes phabricator, arcanist and other resources

export PHABRICATOR_ENV=custom/myconfig
export PATH=$PHABRICATOR_PATH/phabricator/bin:$PATH
export PATH=$PHABRICATOR_PATH/arcanist/bin:$PATH
export PATH=$PHABRICATOR_PATH/libphabricator-indt/bin:$PATH

function tenaz() {
	cat "$1" | arc paste --title "$1"
}
