ENV_NAME="okular"

export INSTALL_PREFIX=$PWD/install
export PATH=$INSTALL_PREFIX/bin:$PATH
export KDEDIRS=$INSTALL_PREFIX:$(kde4-config --prefix)

alias cmake="cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX"
alias ack="ack --ignore-dir=install --ignore-dir=build"

# cmake CMakeLists.txt
# make
# make install
# kbuildsycoca4
